//State de productos

export const OBTERNER_PRODUCTOS = "OBTERNER_PRODUCTOS";

//Seleccionar producto

export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";

//CONFIMAR PEDIDO

export const CONFIRMAR_PEDIDO = "CONFIRMAR_PEDIDO";
